apiVersion: v1
data:
    mongodb-root-password: ENC[AES256_GCM,data:GOZjX0kt6lw6G276bz4td5qV7+y2r3DB,iv:Mof3lcfHBrXfcrU6qhcCSMjQYHkegX4h81zG6Uwrtbo=,tag:zRNfO26ZCXWnWrXSl9ZW5Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mongodb-password
    namespace: infrastructure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-03T09:00:15Z"
    mac: ENC[AES256_GCM,data:N6E62HShf487G4P/FalMiI1sFXOrlH0V7JHbQevqYd+hRrATjoc5Sj5fMUNhFNypoCEUa3tUhH6K1drzcFjbHFQqLTGU0DYC28lADyBi5kAeWN8NnIdu6UkzAs29UluPae/GYO9wt5DJ1sDQ1917dRBiV8EP+eZ2Kjt+rL7kHmA=,iv:ynMn5lTq2evpOe0lXe3Q/MR5P2YjgC6DnkGDBbWXu1E=,tag:XdEczxTW5KVVabFZ7knLxQ==,type:str]
    pgp:
        - created_at: "2021-09-03T09:00:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8B53HsG2KjLAQwA13y1f3mDoF+qCcLDdjnYtUfYQkGcOghZJb1tAo+uIT25
            gosJRDjZvuh2QfHqajrBC9IouwcL/otStA4kR7Lrg0ovpL5eb22XdjYvuDNU0F0B
            IkLFb6kHBoLrLJXmZfiYm/q3ygrTvGbQtctfCgM4lyoL7xdGnAoTRk4dzBrLaofg
            RnWfcy/DZ0H0WU49MbKFxXadEpfmLZa0UXRopMBfKDREPsIBr0NNhmgSKMtyf2oJ
            AIo3tTMW/IiBqT4n9BJRFzWaUkGoD4WyI5lcIAriCpKxP2NhgzRtEccQF/4ARK5Y
            v/ms+AKD5h5BbLB6wrHOyNzOAbe2ytvq+oB+UyU5Xq9HCoJWwzjZ0vS5WOdxSCUB
            wW+W5e2U05+fTARyoDZJ6qWhCJxIFwfg9ShOLQgUMw+2R3K15dJ9UaTwOkOyD+nu
            4umEQix8hImjNDIpAOOPKvBAaFyycumq2oJNialt4KhyGl1sisU2iEdGfjtEL3To
            QiGQ0nq7LPQczlOlW12G1GgBCQIVGDSojBFljvC95HlZv39B15EccY1KshplDVRW
            NHSh25GqYwWGjsJtrd9Ll1XM74nxyHkt/uAvepcEa+M4Dk5RfPgpTBSsJrg42TV2
            TAXW2c/RQ9o09tl/kFWbJTwgyzy7RVOg7A==
            =B0nz
            -----END PGP MESSAGE-----
          fp: 22E48EE28F14874A41A66750C7EF1B6052387A98
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
