apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
spec:
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "10.25.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 10
  values:
    service:
      nameOverride: mongodb
    auth:
      existingSecret: mongodb-password
    persistence:
      enabled: true
      storageClass: do-block-storage

    
