apiVersion: v1
data:
    postgresql-password: ENC[AES256_GCM,data:ictQ8t08ZeMNSvc7,iv:rxCCeuky96w0TKJcTjfg5W3h3UtVRWMeRJxqKmIMiQw=,tag:47oFTkcfgNzygK/Ylk8g+w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: postgresql-password
    namespace: infrastructure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-03T03:39:57Z"
    mac: ENC[AES256_GCM,data:qBlF86OIP4ABL6rc4wDhRd1eUn87cezYZhsEv+RUV496zQKyqWFXDYLKxuJl2/8uDa0wuTX9+vEGX31SOQSZ7DbcQUSgTrI5MNa1WdoE0KY/Pfkfr7us7qGCoj3s5TM/FWWUYpbhJrYQkDQ8U+54yYqbJAaWHzRgUmXQXx2eJNc=,iv:OSjwLxGSShtYMV+O8GatjOY5mMNPLb4NYW+Ek1TCiOI=,tag:lE/aNRlspXA3KHy4Kv3QfA==,type:str]
    pgp:
        - created_at: "2021-09-03T03:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8B53HsG2KjLAQv/WEd5MdJ9lvEDFaZ05GBYf69vfL9VC70PEyEbUsDV58hL
            zKxv0ZZp/vpmxbeBFeXzfAhp3V7qfCnMANLI8cXa8s8rWZSnKoW8s9za+rYmK3kB
            0jSPUsVd9GXQ1Ry5/CjUXoNwEA+8imFlsqySTQ0xU5VWdEsv/U1ke2DZpFscq82p
            xc7d80zZRs8NPH/AiUT6Y6ncYCfU5rEu1GDOfHo2GtX5N3N+yuzLx1DQuDVxf4GO
            uGQjlCjGnqdEuG0pLXFikLTGTvVTNO7mE5sK/82Vlb3RBxdReMwJFAVQxaill6ZU
            ePa7a4iBk/8KXSijnq56V0ecbbF4aY9j58xyEZows/QBBCYXMbDt8+g+XbPjEsP0
            ZC5yBr093m8deOri3jlAShaNA5VKbjWve+341SXRaNUb8uzIPQB7IOMPD9lbvxgf
            HqtLVQMK/Vlvmk6lxeT1+qj91tyabD9qbaLiSgjOCY0j4e2rEx81cKNj+xTXQm7i
            q8dXbAT8nEVEge/yaUfb1GYBCQIV/EpRIU/w9JliF6BcWH02XdG7j0VBRhPdm+P8
            V15KWDc5Mz2HXld1bGilr0ZdAQ/5xqbYzpej9KWBA6OCy1Sj74bOkAQ91Q7aROXc
            qt7DV7T0MMb9POw78qXSreTBhClDt0M=
            =1U7v
            -----END PGP MESSAGE-----
          fp: 22E48EE28F14874A41A66750C7EF1B6052387A98
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
