apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - namespace.yaml
  - nginx
  - cert-manager
  # - cert-manager-settings
  - external-dns
  - auth
  - mongodb
