apiVersion: v1
data:
    password: ENC[AES256_GCM,data:24D9lZMZcWARlUP98xnZBDsJJe22/3wLtaNvAQ==,iv:45dSnUtiwcy9/Y6VWh4dOZqg4R7JFUFLly2P/I3lTFY=,tag:/XKc/AeLRX0qNlxMLF3oLg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-password
    namespace: infrastructure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-03T03:58:50Z"
    mac: ENC[AES256_GCM,data:OtTpE+X3JKr6MFK0CXjTBou3GmAnxwclnBfuI6/xbHX9/+CtK3gBPuk6HpZHWPt7538ZfIYyPWwniNm2HASGFjbkBy3EPJXOR9Txx7k0CiEBFi/MGXjiT/7q9TvpVdrfhXqOEFxFFIj5+HieoMzXxzVg1JHxA8McPG+WaCYFjBE=,iv:NqWqmTS80tO4RihZ79Qhe+J9+uuCInUdZoMbfn8OoV8=,tag:GL8RuulxGUGeOGllIzgHYg==,type:str]
    pgp:
        - created_at: "2021-09-03T03:58:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8B53HsG2KjLAQv8DBr8QGcMMh+Q6bfDsj21ClIWg1yzrzhOSO6WTgs3kTVy
            QuP+zs+CD9/66M679wql/UnRTwS3yornTB8fUcKF06DBRLEOzxKL+Aqcv4vd1ghh
            dH0AKJFzJL8qoksaX5WebPo9hei2128M1iJ5T+6q+5W9fuKOTB0xQpyh4RbvhL6M
            zrdL4BCjMXr3+RHi1aB3GQui0PPRgpsoy063JhlLhx6Nnpin84pmYDmZerKjHRaV
            oVquvrZmDQUFC3Zf0vy3CPcYXGCxU+v7sB6ib8tNbD93dltiGpS43Y0evsJykI4h
            gbNosGaSl7J94Ns1ZRyw9fiLeGP2XXCEJWwNCnwCnqJWqlZhQZMNh4QYU3NcHU7M
            ah3JJ86YkrkexyQx0E5AH0FJfQSiNiIAGDkqR1MJvLISzE5X5E4E1StM0eLwrApK
            i6bIG3m2E+T3aLOd/hFE4EpI89aM7Ydix7/sOZ22N4DCyDaaue7tkfLsYkGX48aH
            6EfjWhrfYg33HXS9S0/v1GgBCQIVfsnn/G6XlptiBqYwel8PQSw/N8Q7tMVHhVKi
            InhmLD8tdndlKv6+jih8qJ/7bzGMhpVbF8/WnjCIRFuDCQUM6SrTfGkqNkXb0iuK
            gTD1b7mbOBpysXnm7gbqKUFbCa5BsLlChg==
            =wi1s
            -----END PGP MESSAGE-----
          fp: 22E48EE28F14874A41A66750C7EF1B6052387A98
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
