apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
      version: 15.0.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 10
  # Default values
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      rules:
        - host: keycloak.staging.labelwarehouse.sheepieslab.com
          paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
      - hosts:
        - keycloak.staging.labelwarehouse.sheepieslab.com
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
