apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "5.6.14"
  interval: 1h0m0s
  install:
    remediation:
      retries: 10
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    publishService:
      # see https://github.com/kubernetes/ingress-nginx/blob/b1c8e3047ba31d7ea78f6e0915d187db75230ba5/charts/ingress-nginx/templates/controller-deployment.yaml#L83
      # when traffics are forward to the ingress, the external ip address is published.
      enabled: true
    extraArgs:
      default-ssl-certificate: infrastructure/labelwarehouse-staging
    #   configmap: infrastructure/nginx-configmap
    # configMapNamespace: infrastructure
